### ISSUE TITLE
EXCeption on first start

### ISSUE THREAD

**Issue by khr15714n** [malahx/QuickStart#1]
only Quick(s) installed

[WRN             ] HighlightingSystem : Framebuffer depth data is not available and can't be used to occlude highlighting. Highlighting occluders enabled.
[WRN             ] [HighLogic]: =========================== Scene Change : From LOADING to MAINMENU =====================
[                ] AddonLoader: Instantiating addon 'QuickGoTo' from assembly 'QuickGoTo'
[                ] AddonLoader: Instantiating addon 'QStockToolbar' from assembly 'QuickGoTo'
[                ] AddonLoader: Instantiating addon 'QuickHide' from assembly 'QuickHide'
[                ] AddonLoader: Instantiating addon 'QStockToolbar' from assembly 'QuickHide'
[                ] AddonLoader: Instantiating addon 'QuickMute' from assembly 'QuickMute'
[                ] AddonLoader: Instantiating addon 'QStockToolbar' from assembly 'QuickMute'
[                ] AddonLoader: Instantiating addon 'QuickRevert' from assembly 'QuickRevert'
[                ] AddonLoader: Instantiating addon 'QStockToolbar' from assembly 'QuickRevert'
[                ] AddonLoader: Instantiating addon 'QStockToolbar' from assembly 'QuickScroll'
[                ] QuickGoTo(1.20): Settings Loaded
[                ] QuickMute(1.06): Settings Loaded
[                ] QuickRevert(2.11): Reset data
[                ] [ModuleManager] Total loading Time = 16.539s
[                ] QuickStart(1.12): MainMenu Loaded
[WRN             ] QuickStart(1.12): The last game found: default
[                ] ExperienceSystem: Found 0 trait types
[                ] ExperienceSystem: Found 9 effect types
[                ] ScenarioTypes: List Created 12 scenario types loaded from 12 loaded assemblies.
[EXC             ] InvalidOperationException: Operation is not valid due to the current state of the object
    System.Linq.Enumerable.Last[ProtoVessel](IEnumerable`1 source, System.Func`2 predicate, Fallback fallback)
    System.Linq.Enumerable.Last[ProtoVessel](IEnumerable`1 source, System.Func`2 predicate)
    QuickStart.QuickStart.LastProtoVessel (.Game game)
    QuickStart.QuickStart+<QStart>c__Iterator0.MoveNext ()
[                ] QuickMute(1.06): Unmute
[                ] Launcher here(in write): True

**Comment by malahx** [comment]
Hello, it's a known bug, but I haven't took the time to found it.
Can you send me your savegame? I think it can be usefull if I see this bug with my debug information.

**Comment by khr15714n** [comment]
It was a fresh install, only your quick(s) beside squad
log above has no other lines except log

**Comment by malahx** [comment]
Ok, if it is on a new savegame I think it can be easy to find it, thanks.
